name: "Build docker image"
on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  REPOSITORY: omevton/mevton-borrower

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.REPOSITORY }}:latest
            ${{ env.REPOSITORY }}:${{ github.sha }}
          cache-to: type=local,dest=/tmp/docker-cache
          cache-from: type=local,src=/tmp/docker-cache,mode=max